### ISSUE TITLE
Magazine website

### ISSUE THREAD

**Issue by lata-11** [PeanutCoffee/MiniProjects#204]
I want to add my magazine website project created purely by css and html.

**Comment by Wilson0406** [comment]
@lata-11 go ahead, add the codes and create a pr. Also attach a screenshot of the website here.

**Comment by lata-11** [comment]
I am trying to push my commit but it gives me this error please help.
![image](https://user-images.githubusercontent.com/103296906/197681089-929dd76f-e151-44eb-afd2-4c8e991de5ca.png)

**Comment by Wilson0406** [comment]
> I am trying to push my commit but it gives me this error please help. ![image](https://user-images.githubusercontent.com/103296906/197681089-929dd76f-e151-44eb-afd2-4c8e991de5ca.png)

Refer this: 
https://stackoverflow.com/questions/47465644/github-remote-permission-denied

**Comment by riddhitech** [comment]
Please assign me this issue.
