### ISSUE TITLE
Random Quote Generator Website using HTML , CSS and JavaScript .

### ISSUE THREAD

**Issue by octosapien** [PeanutCoffee/MiniProjects#205]
The code I want to contribute is of a Random Quote Generator Website that uses HTML , CSS and JavaScript .
The styling has been done using a separately created CSS stylesheet .
A separate app.js file has been used to implement the required functionalities so as to make the page dynamic .

**Comment by octosapien** [comment]
Please assign me this issue .

**Comment by avezqureshi14** [comment]
hey @Wilson0406  i also want to work on this project

**Comment by Wilson0406** [comment]
@avezqureshi14 upload the codes and create a new pr.
