### ISSUE TITLE
Login UI using Jetpack Compose

### ISSUE THREAD

**Issue by utkarsh006** [PeanutCoffee/MiniProjects#70]
- Want to contribute a UI for Login Screen in android to this repository.
- Tech Stack : Kotlin, Jetpack Compose.
- Do consider this issue under hacktoberfest.

**Comment by utkarsh006** [comment]
@PeanutCoffee Kindly give the label as hacktoberfest to the issues.

**Comment by PeanutCoffee** [comment]
hacktoberfest-accepted label had already been given.

**Comment by utkarsh006** [comment]
![Screenshot (182)](https://user-images.githubusercontent.com/94545831/195973666-0a86ce9a-7b27-49b9-a91d-17a8c78f547a.png)
@PeanutCoffee Kindly read second point.

**Comment by niteshk700** [comment]
assign me please
